FROM node:22-alpine
WORKDIR /app
COPY package.json package-lock.json* ./
COPY tsconfig.json ./
COPY apps ./apps
COPY packages ./packages
COPY infrastructure/migrations ./infrastructure/migrations
RUN npm ci
RUN chown -R node:node /app
USER node
CMD ["npm", "run", "api"]
